version: '3.8'

services:
  backend:
    build:
      context: .
    image: csge-backend:1.0.0
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_BUCKET=${MINIO_BUCKETS}
      - MINIO_BUCKET_INVOICES=${MINIO_BUCKET_INVOICES}
      - MINIO_BUCKET_LOGOS=${MINIO_BUCKET_LOGOS}
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console web
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: ["/usr/local/bin/create-buckets.sh"]
    env_file:
      - .env
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_API=${MINIO_API}
      - MINIO_BUCKETS=${CREATE_MINIO_BUCKETS}
    volumes:
      - ./scripts/create-buckets.sh:/usr/local/bin/create-buckets.sh:ro

volumes:
  minio_data:
