export enum ESTATUS_ORDEN_DE_SERVICIO {
    PENDIENTE = "PENDIENTE",
    ACTIVA = "ACTIVA",
    COTEJADA = "COTEJADA",
    PAGO_APROBADO = "PAGO_APROBADO",
    PAGADA = "PAGADA",
    CANCELADA = "CANCELADA"
}