export enum EstatusOrdenDeServicio {
    PENDIENTE = "PENDIENTE",
    ACTIVA = "ACTIVA",
    COTEJADA = "COTEJADA",
    PAGO_APROBADO ="PAGO_APROBADO",
    PAGADA = "PAGADA",
    CANCELADA = "CANCELADA"
}