export enum TipoCampaña {
    INFORMATIVA = "INFORMATIVA",
    CONVOCATORIA = "CONVOCATORIA",
    PROGRAMA = "PROGRAMA",
    INFORME = "INFORME",
    EVENTO = "EVENTO",
    PUBLICACIONES_OFICIALES = "PUBLICACIONES_OFICIALES",
    SERVICIOS_GENERALES = "SERVICIOS_GENERALES"
}