export enum MODULE_ENUM {
    CAMPAIGN = 'CAMPAÑA',
    INVOICE = 'FACTURA',
    ORDER = 'ORDEN',
    PROVIDER = "PROVEEDOR",
    MASTER_CONTRACT = "CONTRATO MAESTRO",
    AMMENDMENT_CONTRACT = "CONTRATO MODIFICATORIO",
    STATION = "ESTACIONES"
}

