export enum ESTATUS_DE_FIRMA {
    CANCELADA = 'CANCELADA',
    APROBADA = 'APROBADA',
    PENDIENTE_DE_FIRMA = 'PENDIENTE DE FIRMA',
    NOT_CARRIED_OUT = 'NO CONCRETADO',
    SIGNED_REVIEW = 'COTEJADO'
}

