export enum INVOICE_STATUS {
    RECIBIDA = 'RECIBIDA',
    CONTEJADA = "COTEJADA",
    APROBADA = 'APROBADA',
    PARTIAL_PAY = 'PAGO PARCIAL',
    PROGRMADA_PARA_PAGO = 'PROGRAMADA PARA PAGO',
    PAGADA = 'PAGADA',
    CANCELADA = 'CANCELADA'
}