export enum INVOICE_STATUS {
    RECIBIDA = 'RECIBIDA',
    CONTEJADA ="COTEJADA",
    APROBADA = 'APROBADA',
    PROGRMADA_PARA_PAGO = 'PROGRAMADA PARA PAGO',
    PAGADA = 'PAGADA',
    CANCELADA = 'CANCELADA'
}