export const enum CAMPAIGN_TYPE_REPORT {
    AMOUNTS_TRACKING_BY_PROVIDER = "AMOUNTS_TRACKING_BY_PROVIDER",
    AMOUNTS_TRACKING_BY_SERVICE_TYPE = "AMOUNTS_TRACKING_BY_SERVICE_TYPE",
    AMOUNTS_TRACKING_BY_CAMPAIGN = "AMOUNTS_TRACKING_BY_CAMPAIGN",
    PERCENTAGE_OF_SERVICE_ORDERS = "PERCENTAGE_OF_SERVICE_ORDERS"
}